WatchMarket/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from WatchMarket.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('profiles/', include('profiles.urls')),
    path('watches/', include('watches.urls')),
    path('reviews/', include('reviews.urls')),
    path('wishlist/', include('wishlist.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from profiles.views import UserCreationView, UserUpdateView, UserDetailView

app_name = 'profiles'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='profiles/registration/login.html'
    ), name='user-login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='profiles/registration/logged_out.html'
    ), name='user-logout'),
    path('register/', UserCreationView.as_view(), name='user-registration'),
    path('change_password/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('home'),
        template_name='profiles/registration/change_password.html'
    ), name='change-password'),
    path('<int:pk>/detail/', UserDetailView.as_view(), name='user-detail'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='user-update'),
]

reviews/urls.py
from django.urls import path

from reviews.views import WriteReviewView, ListReviewsOfSeller, ReviewUpdate, ReviewDelete

app_name = 'reviews'

urlpatterns = [
    # la pk è utilizzata per salvarsi il venditore di cui si sta facendo la review
    path('<int:pk>/write/', WriteReviewView.as_view(), name='leave-review'),
    path('<int:pk>/sellerreviews/', ListReviewsOfSeller.as_view(), name='seller-reviews'),
    path('<int:pk>/update/', ReviewUpdate.as_view(), name='review-update'),
    path('<int:pk>/delete/', ReviewDelete.as_view(), name='review-delete'),

]

watches/urls.py
from django.urls import path# nel contesto inserisco tutta la ricerca per poter ripopolare i campi e far andare la pagination

from watches.views import WatchSaleAnnouncementView, WatchSalePostView, SaleAnnouncementList, PersonalSaleAnnouncement, \
    WatchSaleAnnouncementUpdate, WatchSaleAnnouncementDelete, WatchSearchView, ProfileShopView, ConfirmBuyView, \
    BoughtView

app_name = 'watches'

urlpatterns = [
    path('sell/', WatchSaleAnnouncementView.as_view(), name='insert_sale_announcement'),
    path('announcement/<int:pk>/detail/', WatchSalePostView.as_view(), name='sale_announcement_detail'),
    path('announcement/<int:pk>/update/', WatchSaleAnnouncementUpdate.as_view(), name='sale_announcement_update'),
    path('announcement/<int:pk>/delete/', WatchSaleAnnouncementDelete.as_view(), name='sale_announcement_delete'),
    path('list/', SaleAnnouncementList.as_view(), name='sale_announcement_list'),
    path('list/search/', WatchSearchView.as_view(), name='sale_announcement_search_list'),
    path('mylist/', PersonalSaleAnnouncement.as_view(), name='my_sale_announcement_list'),
    path('<int:pk>/shop/', ProfileShopView.as_view(), name='sale_shop_list'),
    path('<int:pk>/confirmation/', ConfirmBuyView.as_view(), name='confirm_purchase'),
    path('<int:pk>/bought/', BoughtView.as_view(), name='watch_bought'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser

# https://docs.djangoproject.com/en/3.2/topics/auth/customizing/#custom-users-and-the-built-in-auth-forms
from django.db.transaction import on_commit


class UserProfileModel(AbstractUser):
    email = models.EmailField(verbose_name='Email')
    address = models.CharField(max_length=100, blank=True)
    is_seller = models.BooleanField(default=False,
                                    verbose_name="Are you a seller ?")
    user_photo = models.ImageField(upload_to='profiles/photos',
                                   verbose_name='Profile pic',
                                   blank=True)

profiles/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.contrib.auth.forms import UserCreationForm

from profiles.models import UserProfileModel


class UserProfileForm(UserCreationForm):
    helper = FormHelper()
    helper.form_id = 'user_profile_crispy_form'
    helper.form_method = 'POST'
    helper.add_input(Submit('save', 'Save'))
    helper.inputs[0].field_classes = 'btn btn-success'

    class Meta:
        model = UserProfileModel
        fields = ['first_name',
                  'last_name',
                  'address',
                  'email',
                  'username',
                  'is_seller',
                  'user_photo']


class UserUpdateForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_id = 'user_profile_crispy_form'
    helper.form_method = 'POST'
    helper.add_input(Submit('save', 'Save'))
    helper.inputs[0].field_classes = 'btn btn-success'

    class Meta:
        model = UserProfileModel
        fields = ['first_name',
                  'last_name',
                  'address',
                  'email',
                  'username',
                  'user_photo']

profiles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView

from profiles.forms import UserProfileForm, UserUpdateForm
from profiles.mixins import IsMyselfMixin
from profiles.models import UserProfileModel


# view per creare un nuovo utente
class UserCreationView(SuccessMessageMixin, CreateView):
    model = UserProfileModel
    form_class = UserProfileForm
    template_name = 'profiles/CRUD/create_user.html'
    success_message = 'User created correctly!'
    success_url = reverse_lazy('profiles:user-login')


# view per aggiornare un utente, controllando che sia chi fa la richiesta a poterlo fare
class UserUpdateView(SuccessMessageMixin, LoginRequiredMixin, IsMyselfMixin, UpdateView):
    model = UserProfileModel
    form_class = UserUpdateForm
    template_name = 'profiles/CRUD/update_user.html'
    success_message = 'User updated correctly!'

    def get_success_url(self):
        return reverse_lazy('profiles:user-detail', kwargs={'pk': self.kwargs['pk']})


# un utente non può eliminarsi da solo

# view per poter visualizzare tutti i dettagli di un certo utente
class UserDetailView(DetailView):
    model = UserProfileModel
    template_name = 'profiles/CRUD/user_detail.html'

profiles/templates/profiles/CRUD/create_user.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Register
{% endblock %}

{% block content %}
    <h1>Register to WatchMarket</h1>
    {% crispy form %}
    <a class="btn" href="{% url 'home' %}">Cancel</a>
{% endblock %}

profiles/templates/profiles/CRUD/update_user.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    User: Update
{% endblock %}

{% block content %}
    <h1>User profile update</h1>
    {% crispy form %}
    <a href="{% url 'profiles:user-detail' user.pk %}" class="btn">Cancel</a>
{% endblock %}

profiles/templates/profiles/CRUD/user_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Details of user {{ object.first_name }} {{ object.last_name }}
{% endblock %}

{% block style %}
    <style>
        .panel.panel-default {
            border-top-width: 3px;
        }
        .panel {
            box-shadow: 0 3px 1px -2px rgba(0,0,0,.14),0 2px 2px 0 rgba(0,0,0,.098),0 1px 5px 0 rgba(0,0,0,.084);
            border: 0;
            border-radius: 4px;
            margin-bottom: 16px;
        }
        .thumb96 {
            width: 96px!important;
            height: 96px!important;
        }
        .thumb48 {
            width: 48px!important;
            height: 48px!important;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="container bootstrap snippets bootdey">
        <div class="row ng-scope">
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-body text-center">
                        {% if object.user_photo %}
                            <div class="pv-lg"><img class="center-block img-responsive img-circle img-thumbnail thumb96" src="{{ object.user_photo.url }}" alt="Profile pic"></div>
                        {% endif %}
                        {% if user.pk == object.pk %}
                            <div class="text-center"><a class="btn btn-primary" href="{% url 'profiles:user-update' object.pk %}">Edit</a></div>
                            <div class="text-center"><a class="btn btn-primary" href="{% url 'profiles:change-password' %}">Change password</a></div>
                            {% if object.is_seller %}
                                <div class="text-center"><a class="btn btn-primary" href="{% url 'reviews:seller-reviews' object.pk %}">Reviews</a></div>
                            {% endif %}
                        {% else %}
                            {% if object.is_seller %}
                                <div class="text-center"><a class="btn btn-primary" href="{% url 'watches:sale_shop_list' object.pk %}">Watches</a></div>
                                <div class="text-center"><a class="btn btn-primary" href="{% url 'reviews:seller-reviews' object.pk %}">Reviews</a></div>
                            {% endif %}
                        {% endif %}

                    </div>
                </div>

            </div>
            <div class="col-md-8">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="h4 text-center">User Information</div>
                        <div class="row pv-lg">
                            <div class="col-lg-2"></div>
                            <div class="col-lg-8">
                                <form class="form-horizontal ng-pristine ng-valid">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputUser1">First Name</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" id="inputUser1" type="text" placeholder="" value="{{ object.first_name }}" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputUser2">Last Name</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" id="inputUser2" type="text" value="{{ object.last_name }}" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputUser3">Address</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" id="inputUser3" type="text" value="{{ object.address }}" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputUser4">Email</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" id="inputUser4" type="text" value="{{ object.email }}" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputUser6">Username</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" id="inputUser6" type="text" value="{{ object.username }}" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputUser7">Is a seller ?</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" id="inputUser7" type="text" value="{{ object.is_seller }}" disabled>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}