WatchMarket/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from WatchMarket.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('profiles/', include('profiles.urls')),
    path('watches/', include('watches.urls')),
    path('reviews/', include('reviews.urls')),
    path('wishlist/', include('wishlist.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from profiles.views import UserCreationView, UserUpdateView, UserDetailView

app_name = 'profiles'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='profiles/registration/login.html'
    ), name='user-login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='profiles/registration/logged_out.html'
    ), name='user-logout'),
    path('register/', UserCreationView.as_view(), name='user-registration'),
    path('change_password/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('home'),
        template_name='profiles/registration/change_password.html'
    ), name='change-password'),
    path('<int:pk>/detail/', UserDetailView.as_view(), name='user-detail'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='user-update'),
]

reviews/urls.py
from django.urls import path

from reviews.views import WriteReviewView, ListReviewsOfSeller, ReviewUpdate, ReviewDelete

app_name = 'reviews'

urlpatterns = [
    # la pk è utilizzata per salvarsi il venditore di cui si sta facendo la review
    path('<int:pk>/write/', WriteReviewView.as_view(), name='leave-review'),
    path('<int:pk>/sellerreviews/', ListReviewsOfSeller.as_view(), name='seller-reviews'),
    path('<int:pk>/update/', ReviewUpdate.as_view(), name='review-update'),
    path('<int:pk>/delete/', ReviewDelete.as_view(), name='review-delete'),

]

watches/urls.py
from django.urls import path# nel contesto inserisco tutta la ricerca per poter ripopolare i campi e far andare la pagination

from watches.views import WatchSaleAnnouncementView, WatchSalePostView, SaleAnnouncementList, PersonalSaleAnnouncement, \
    WatchSaleAnnouncementUpdate, WatchSaleAnnouncementDelete, WatchSearchView, ProfileShopView, ConfirmBuyView, \
    BoughtView

app_name = 'watches'

urlpatterns = [
    path('sell/', WatchSaleAnnouncementView.as_view(), name='insert_sale_announcement'),
    path('announcement/<int:pk>/detail/', WatchSalePostView.as_view(), name='sale_announcement_detail'),
    path('announcement/<int:pk>/update/', WatchSaleAnnouncementUpdate.as_view(), name='sale_announcement_update'),
    path('announcement/<int:pk>/delete/', WatchSaleAnnouncementDelete.as_view(), name='sale_announcement_delete'),
    path('list/', SaleAnnouncementList.as_view(), name='sale_announcement_list'),
    path('list/search/', WatchSearchView.as_view(), name='sale_announcement_search_list'),
    path('mylist/', PersonalSaleAnnouncement.as_view(), name='my_sale_announcement_list'),
    path('<int:pk>/shop/', ProfileShopView.as_view(), name='sale_shop_list'),
    path('<int:pk>/confirmation/', ConfirmBuyView.as_view(), name='confirm_purchase'),
    path('<int:pk>/bought/', BoughtView.as_view(), name='watch_bought'),
]

wishlist/urls.py
from django.urls import path

from wishlist.views import WishListView, add_to_wishlist, remove_from_wishlist

app_name = 'wishlist'


urlpatterns = [
    path('list/', WishListView.as_view(), name='wishlist-all'),
    path('<int:pk>/add/', add_to_wishlist, name='wishlist-add'),
    path('<int:pk>/remove/', remove_from_wishlist, name='wishlist-remove')
]

watches/models.py
from datetime import date

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.
import profiles


CONDITION_CHOICES = (
    ('NEW_NEVER_WORN', 'New/Never worn'),
    ('VERY_GOOD', 'Very Good'),
    ('GOOD', 'Good'),
    ('POOR', 'Poor'),
    ('NOT_WORKING', 'Not working')
)

CASE_MATERIAL_CHOICES = (
    ('STAINLESS_STEEL', 'Stainless Steel'),
    ('WHITE_GOLD', 'White Gold'),
    ('YELLOW_GOLD', 'Yellow Gold'),
    ('ROSE_GOLD', 'Rose Gold'),
    ('PLATINUM', 'Platinum'),
    ('TITANIUM', 'Titanium'),
    ('OTHER', 'Other')
)

BRACELET_MATERIAL_CHOICES = (
    ('STAINLESS_STEEL', 'Stainless Steel'),
    ('WHITE_GOLD', 'White Gold'),
    ('YELLOW_GOLD', 'Yellow Gold'),
    ('ROSE_GOLD', 'Rose Gold'),
    ('PLATINUM', 'Platinum'),
    ('TITANIUM', 'Titanium'),
    ('LEATHER', 'Leather'),
    ('RUBBER', 'Rubber'),
    ('OTHER', 'Other')
)


class WatchSaleAnnouncementModel(models.Model):
    watch_brand = models.CharField(max_length=100,
                                   verbose_name='Brand of the watch')
    watch_model = models.CharField(max_length=100,
                                   verbose_name='Model of the watch')
    watch_reference = models.CharField(max_length=50,
                                       verbose_name='Reference number of the watch',
                                       blank=True)
    watch_price = models.FloatField(verbose_name='Price',
                                    validators=[MinValueValidator(1)])
    watch_seller = models.ForeignKey(profiles.models.UserProfileModel,
                                     related_name='watch_seller',
                                     on_delete=models.PROTECT)
    watch_description = models.TextField(verbose_name='Description',
                                         blank=True)
    watch_photos = models.ImageField(upload_to='watches/photos',
                                     verbose_name='Pic of the watch')
    watch_year = models.IntegerField(verbose_name='Year of production',
                                     validators=[MinValueValidator(date.min.year),
                                                 MaxValueValidator(date.today().year)])
    watch_condition = models.CharField(max_length=500,
                                       choices=CONDITION_CHOICES,
                                       verbose_name='Select watch\'s condition')
    watch_size = models.IntegerField(verbose_name='Size of the case (mm)',
                                     validators=[MinValueValidator(1)])
    watch_case_material = models.CharField(choices=CASE_MATERIAL_CHOICES,
                                           verbose_name='Select your watch\'s case material',
                                           max_length=500)
    watch_bracelet_material = models.CharField(choices=BRACELET_MATERIAL_CHOICES,
                                               verbose_name='Select your watch\'s bracelet material',
                                               max_length=500)
    create_date = models.DateTimeField(auto_now=True)
    is_bought = models.BooleanField(default=False)

watches/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from watches.models import WatchSaleAnnouncementModel


class WatchSaleAnnouncementForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_id = 'watch_sale_announcement_crispy_form'
    helper.form_method = 'POST'
    helper.add_input(Submit('save', 'Save'))
    helper.inputs[0].field_classes = 'btn btn-success'

    class Meta:
        model = WatchSaleAnnouncementModel
        fields = ['watch_brand',
                  'watch_model',
                  'watch_reference',
                  'watch_price',
                  'watch_description',
                  'watch_photos',
                  'watch_year',
                  'watch_condition',
                  'watch_size',
                  'watch_case_material',
                  'watch_bracelet_material']

watches/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView

from django.db.models import Q, Max

from WatchMarket import settings
from profiles.models import UserProfileModel
from watches.mixins import IsSellerMixin, IsOwnerMixin, IsNotOwnerMixin

from watches.forms import WatchSaleAnnouncementForm
from watches.models import WatchSaleAnnouncementModel


# view utilizzata per l'aggiunta di un nuovo annuncio sul sito
class WatchSaleAnnouncementView(SuccessMessageMixin, LoginRequiredMixin, IsSellerMixin, CreateView):
    model = WatchSaleAnnouncementModel
    template_name = 'watches/CRUD/createSaleAnnouncement.html'
    form_class = WatchSaleAnnouncementForm
    success_message = 'Watch inserted correctly!'

    def form_valid(self, form):
        form.instance.watch_seller = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('watches:sale_announcement_detail', kwargs={'pk': self.object.pk})


# view utilizzata per l'aggionamento di un annuncio già inserito, controllo che solo chi è loggato, venditore e
# proprietario possa modificare l'oggetto
class WatchSaleAnnouncementUpdate(SuccessMessageMixin, LoginRequiredMixin, IsSellerMixin, IsOwnerMixin, UpdateView):
    model = WatchSaleAnnouncementModel
    template_name = 'watches/CRUD/updateSaleAnnouncement.html'
    form_class = WatchSaleAnnouncementForm
    success_message = 'Watch edited correctly!'

    def get_success_url(self):
        return reverse_lazy('watches:sale_announcement_detail', kwargs={'pk': self.kwargs['pk']})


# view per la rimozione di un annuncio,  controllo che solo chi è loggato, venditore e proprietario
# possa modificare l'oggetto
class WatchSaleAnnouncementDelete(LoginRequiredMixin, IsSellerMixin, IsOwnerMixin, DeleteView):
    model = WatchSaleAnnouncementModel
    template_name = 'watches/CRUD/deleteSaleAnnouncement.html'
    success_url = reverse_lazy('watches:my_sale_announcement_list')
    success_message = 'Watch deleted correctly!'

    def delete(self, request, *args, **kwargs):
        messages.success(request, self.success_message)
        return super(WatchSaleAnnouncementDelete, self).delete(request, *args, **kwargs)


# creo una view dove posso far vedere tutti gli oggetti simili a quello che si sta visualizzando.
# nel queryset ottengo i simili, nel context carico staticamente un oggetto da visualizzare
class WatchSalePostView(ListView):
    model = WatchSaleAnnouncementModel
    template_name = 'watches/CRUD/announcementDetail.html'
    WATCH_PRICE_DELTA = 5000

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super(WatchSalePostView, self).get_context_data(*args, **kwargs)

        context['object_detail'] = WatchSaleAnnouncementModel.objects.get(pk=self.kwargs['pk'])

        return context

    def get_queryset(self):
        watch = WatchSaleAnnouncementModel.objects.get(pk=self.kwargs['pk'])

        # queryset di base con tutti gli oggetti che non sono stati venduti
        base_queryset = WatchSaleAnnouncementModel.objects.filter(is_bought=False)

        base_queryset = base_queryset.exclude(pk=watch.pk)

        queryset_only_brand = base_queryset.filter(watch_brand=watch.watch_brand)
        queryset_brand_and_model = base_queryset.filter(watch_brand=watch.watch_brand,
                                                        watch_model=watch.watch_model)
        queryset_price_range = base_queryset.filter(watch_price__range=(watch.watch_price - self.WATCH_PRICE_DELTA,
                                                                        watch.watch_price + self.WATCH_PRICE_DELTA))

        queryset_size = base_queryset.filter(watch_size=watch.watch_size)

        queryset_bracelet_material = base_queryset.filter(watch_bracelet_material=watch.watch_bracelet_material)

        queryset_case_material = base_queryset.filter(watch_case_material=watch.watch_case_material)

        # ritorno la combinazione di tutti gli orologi cercati, senza duplicati di default (altrimenti all=True)
        # i parametri comprendono:
        # - stesso il brand
        # - stesso il brand e modello
        # - stessa la dimensione della cassa
        # - stessi materiali di costruzione
        queryset = queryset_only_brand.union(queryset_brand_and_model, queryset_size, queryset_bracelet_material,
                                             queryset_case_material)

        # ritorno il queryset con un delta di prezzi fissato
        return queryset.intersection(queryset_price_range)


# view per vedere tutti gli annunci pubblicati
class SaleAnnouncementList(ListView):
    model = WatchSaleAnnouncementModel
    template_name = 'watches/watchesList.html'
    paginate_by = 10


# view per vedere gli annunci pubblicati da me (loggato)
class PersonalSaleAnnouncement(LoginRequiredMixin, ListView):
    model = WatchSaleAnnouncementModel
    template_name = 'watches/personalList.html'
    paginate_by = 10

    def get_queryset(self):
        return WatchSaleAnnouncementModel.objects.filter(
            watch_seller=self.request.user
        ).order_by('create_date')


# view per vedere gli annunci solo di un certo utente
class ProfileShopView(ListView):
    model = WatchSaleAnnouncementModel
    template_name = 'watches/profileShop.html'
    paginate_by = 10

    def get_queryset(self):
        return WatchSaleAnnouncementModel.objects.filter(
            watch_seller_id=self.kwargs['pk']
        )

    def get_context_data(self, *args, **kwargs):
        # così ottengo il nome dell'utente e posso tornare indietro
        context = super(ProfileShopView, self).get_context_data(*args, **kwargs)

        context['user_shop'] = UserProfileModel.objects.get(pk=self.kwargs['pk'])

        return context


# view per la ricerca di oggetti per modello, brand e diversi altri range di parametri
class WatchSearchView(ListView):
    model = WatchSaleAnnouncementModel
    template_name = 'watches/watchesList.html'
    paginate_by = 10

    # rimetto i dati nel contesto per ripopolare la ricerca e far funzionare la pagination con
    # la query che c'era prima
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WatchSearchView, self).get_context_data(**kwargs)

        sorting_type = self.request.GET.get('order-by') or 'p-asc'

        if sorting_type == 'p-asc':
            sorting_type = 'watch_price'
        elif sorting_type == 'p-desc':
            sorting_type = '-watch_price'
        elif sorting_type == 'date-asc':
            sorting_type = 'create_date'
        elif sorting_type == 'date-desc':
            sorting_type = '-create_date'
        elif sorting_type == 'year-asc':
            sorting_type = 'watch_year'
        elif sorting_type == 'year-desc':
            sorting_type = '-watch_year'

        context['query_brand'] = self.request.GET.get('query-brand') or None
        context['query_model'] = self.request.GET.get('query-model') or None
        context['query_reference'] = self.request.GET.get('ref-number') or None
        context['min_price'] = self.request.GET.get('start-price') or 0
        context['max_price'] = self.request.GET.get('end-price') or WatchSaleAnnouncementModel.objects.all() \
            .aggregate(Max('watch_price'))['watch_price__max']
        context['min_year'] = self.request.GET.get('start-year') or 0
        context['max_year'] = self.request.GET.get('end-year') or WatchSaleAnnouncementModel.objects.all() \
            .aggregate(Max('watch_year'))['watch_year__max']
        context['min_case_size'] = self.request.GET.get('start-case-size') or 0
        context['max_case_size'] = self.request.GET.get('end-case-size') or WatchSaleAnnouncementModel.objects.all() \
            .aggregate(Max('watch_size'))['watch_size__max']
        context['case_material'] = self.request.GET.get('case-material') or None
        context['bracelet_material'] = self.request.GET.get('bracelet-material') or None
        context['conditions'] = self.request.GET.get('conditions') or None
        context['sorting_type'] = sorting_type
        context['is_search'] = True

        return context

    def get_queryset(self):
        # ottengo tutti i filtri dalla richiesta in get
        query_brand = self.request.GET.get('query-brand') or None
        query_model = self.request.GET.get('query-model') or None
        query_reference = self.request.GET.get('ref-number') or None

        min_price = self.request.GET.get('start-price') or 0
        max_price = self.request.GET.get('end-price') or WatchSaleAnnouncementModel.objects.all() \
            .aggregate(Max('watch_price'))['watch_price__max']  # ottengo il massimo di tutti gli oggetti nel db

        min_year = self.request.GET.get('start-year') or 0
        max_year = self.request.GET.get('end-year') or WatchSaleAnnouncementModel.objects.all() \
            .aggregate(Max('watch_year'))['watch_year__max']

        min_case_size = self.request.GET.get('start-case-size') or 0
        max_case_size = self.request.GET.get('end-case-size') or WatchSaleAnnouncementModel.objects.all() \
            .aggregate(Max('watch_size'))['watch_size__max']

        case_material = self.request.GET.get('case-material') or None

        bracelet_material = self.request.GET.get('bracelet-material') or None

        conditions = self.request.GET.get('conditions') or None

        # il sort di default è per data
        sorting_type = self.request.GET.get('order-by') or 'p-asc'

        if sorting_type == 'p-asc':
            sorting_type = 'watch_price'
        elif sorting_type == 'p-desc':
            sorting_type = '-watch_price'

watches/templates/watches/CRUD/announcementDetail.html
{% extends 'base.html' %}
{% load static %}
{% load is_owner_filter %}
{% load check_wishlist %}

{% block title %}
    Details of watch number {{ object_detail.pk }}
{% endblock %}

{% block style %}
    <style>
        .panel.panel-default {
            border-top-width: 3px;
        }
        .panel {
            box-shadow: 0 3px 1px -2px rgba(0,0,0,.14),0 2px 2px 0 rgba(0,0,0,.098),0 1px 5px 0 rgba(0,0,0,.084);
            border: 0;
            border-radius: 4px;
            margin-bottom: 16px;
        }
        .thumb96 {
            width: 96px!important;
            height: 96px!important;
        }
        .thumb48 {
            width: 48px!important;
            height: 48px!important;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="container bootstrap snippets bootdey">
        <div class="row ng-scope">
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-body text-center">
                        <div class="pv-lg"><img class="center-block img-responsive img-circle img-thumbnail thumb96" src="{{ object_detail.watch_photos.url }}" alt="Photo of the watch"></div>
                        <h3 class="m0 text-bold">{{ object_detail.watch_brand }} {{ object_detail.watch_model }}</h3>
                        <p class="m0">Inserted: {{ object_detail.create_date.day }}/{{ object_detail.create_date.month }}/{{ object_detail.create_date.year }}</p>
                        <p class="m0">By: <a href="{% url 'profiles:user-detail' object_detail.watch_seller.pk %}">{{ object_detail.watch_seller.username }}</a></p>
                        {% if user|is_owner:object_detail %}
                            {% if not object_detail.is_bought %}
                                <div class="text-center"><a class="btn btn-primary" href="{% url 'watches:sale_announcement_update' object_detail.pk %}">Edit</a></div>
                            {% endif %}
                            <div class="text-center"><a class="btn btn-primary" href="{% url 'watches:sale_announcement_delete' object_detail.pk %}">Delete</a></div>
                        {% else %}
                            {% if user.is_authenticated %}
                                {% if not object_detail.is_bought %}
                                    <div class="text-center"><a class="btn btn-primary" href="{% url 'watches:confirm_purchase' object_detail.pk %}">Buy</a></div>
                                    {% if not user|is_in_wishlist:object_detail %}
                                        <div class="text-center"><a class="btn btn-primary" href="{% url 'wishlist:wishlist-add' object_detail.pk %}">Add to wishlist</a></div>
                                    {% else %}
                                        <div class="text-center"><a class="btn btn-primary" href="{% url 'wishlist:wishlist-remove' object_detail.pk %}">Remove from wishlist</a></div>
                                    {% endif %}
                                {% else %}
                                    <div class="text-center"><p class="m0">Watch has already been sold!</p></div>
                                {% endif %}
                            {% else %}
                                <p class="m0"><a href="{% url 'profiles:user-login' %}">Login</a> or <a href="{% url 'profiles:user-registration' %}">Register</a> to buy.</p>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="h4 text-center">Watch Information</div>
                        <div class="row pv-lg">
                            <div class="col-lg-2"></div>
                            <div class="col-lg-8">
                                <form class="form-horizontal ng-pristine ng-valid">
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputWatch1">Brand</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" id="inputWatch1" type="text" placeholder="" value="{{ object_detail.watch_brand }}" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputWatch2">Model</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" id="inputWatch2" type="text" value="{{ object_detail.watch_model }}" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputWatch3">Reference Number</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" id="inputWatch3" type="text" value="{{ object_detail.watch_reference }}" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputWatch4">Price</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" id="inputWatch4" type="text" value="{{ object_detail.watch_price }}€" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputWatch5">Description</label>
                                        <div class="col-sm-10">
                                            <textarea class="form-control" id="inputWatch5" disabled>{{ object_detail.watch_description }}</textarea>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputWatch6">Year</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" id="inputWatch6" type="text" value="{{ object_detail.watch_year }}" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputWatch7">Watch Condition</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" id="inputWatch7" type="text" value="{{ object_detail.watch_condition }}" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputWatch8">Watch Size</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" id="inputWatch8" type="text" value="{{ object_detail.watch_size }}" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputWatch9">Watch Case Material</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" id="inputWatch9" type="text" value="{{ object_detail.watch_case_material }}" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputWatch10">Watch Bracelet Material</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" id="inputWatch8" type="text" value="{{ object_detail.watch_bracelet_material }}" disabled>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% if user.is_authenticated and object_list %}
                <div class="panel panel-default hidden-xs hidden-sm w-100">
                    <div class="panel-heading">
                        <div class="panel-title h4 text-center">Similar objects</div>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            {% for object in object_list %}
                                <div class="col-sm-4">
                                    <div class="card" style="width: 18rem;">
                                        <img src="{{ object.watch_photos.url }}" class="card-img-top" alt="{{ object.watch_brand }} {{ object.watch_model }}">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ object.watch_brand }} {{ object.watch_model }}</h5>
                                            <p class="card-text">{{ object.watch_price }}€</p>
                                            {% if object.is_bought %}
                                                <p class="card-text">Item has already been bought!</p>
                                            {% endif %}
                                            <a href="{% url 'watches:sale_announcement_detail' object.pk %}" class="btn btn-primary">See more</a>
                                            {% if user|is_owner:object %}
                                                {% if not object.is_bought %}
                                                    <a href="{% url 'watches:sale_announcement_update' object.pk %}" class="btn btn-primary">Edit</a>
                                                {% endif %}
                                                <a href="{% url 'watches:sale_announcement_delete' object.pk %}" class="btn btn-primary">Delete</a>
                                            {% else %}
                                                {% if user.is_authenticated %}
                                                    {% if not user|is_in_wishlist:object %}
                                                        <a href="{% url 'wishlist:wishlist-add' object.pk %}" class="btn btn-primary">Add to wishlist</a>
                                                    {% else %}
                                                        <a href="{% url 'wishlist:wishlist-remove' object.pk %}" class="btn btn-primary">Remove from wishlist</a>
                                                    {% endif %}
                                                {% endif %}
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

watches/templates/watches/CRUD/createSaleAnnouncement.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    New watch announcement
{% endblock %}

{% block content %}
    <h1>Insert sale announcement</h1>
    {% crispy form %}
    <a href="{% url 'watches:my_sale_announcement_list' %}">Cancel</a>
{% endblock %}

watches/templates/watches/CRUD/deleteSaleAnnouncement.html
{% extends 'base.html' %}

{% block title %}
    Watch Announcement: Delete
{% endblock %}

{% block content %}
    <h1>Sale announcement delete</h1>
    <h3>You're going to delete this watch. Are you sure ?</h3>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Confirm">
        <a href="{% url 'watches:my_sale_announcement_list' %}">Cancel</a>
    </form>
{% endblock %}

watches/templates/watches/CRUD/updateSaleAnnouncement.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Watch Announcement: Update
{% endblock %}

{% block content %}
    <h1>Watch Announcement Update</h1>
    {% crispy form %}
    <a href="{% url 'watches:my_sale_announcement_list' %}">Cancel</a>
{% endblock %}