WatchMarket/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from WatchMarket.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('profiles/', include('profiles.urls')),
    path('watches/', include('watches.urls')),
    path('reviews/', include('reviews.urls')),
    path('wishlist/', include('wishlist.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from profiles.views import UserCreationView, UserUpdateView, UserDetailView

app_name = 'profiles'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='profiles/registration/login.html'
    ), name='user-login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='profiles/registration/logged_out.html'
    ), name='user-logout'),
    path('register/', UserCreationView.as_view(), name='user-registration'),
    path('change_password/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('home'),
        template_name='profiles/registration/change_password.html'
    ), name='change-password'),
    path('<int:pk>/detail/', UserDetailView.as_view(), name='user-detail'),
    path('<int:pk>/update/', UserUpdateView.as_view(), name='user-update'),
]

reviews/urls.py
from django.urls import path

from reviews.views import WriteReviewView, ListReviewsOfSeller, ReviewUpdate, ReviewDelete

app_name = 'reviews'

urlpatterns = [
    # la pk è utilizzata per salvarsi il venditore di cui si sta facendo la review
    path('<int:pk>/write/', WriteReviewView.as_view(), name='leave-review'),
    path('<int:pk>/sellerreviews/', ListReviewsOfSeller.as_view(), name='seller-reviews'),
    path('<int:pk>/update/', ReviewUpdate.as_view(), name='review-update'),
    path('<int:pk>/delete/', ReviewDelete.as_view(), name='review-delete'),

]

watches/urls.py
from django.urls import path# nel contesto inserisco tutta la ricerca per poter ripopolare i campi e far andare la pagination

from watches.views import WatchSaleAnnouncementView, WatchSalePostView, SaleAnnouncementList, PersonalSaleAnnouncement, \
    WatchSaleAnnouncementUpdate, WatchSaleAnnouncementDelete, WatchSearchView, ProfileShopView, ConfirmBuyView, \
    BoughtView

app_name = 'watches'

urlpatterns = [
    path('sell/', WatchSaleAnnouncementView.as_view(), name='insert_sale_announcement'),
    path('announcement/<int:pk>/detail/', WatchSalePostView.as_view(), name='sale_announcement_detail'),
    path('announcement/<int:pk>/update/', WatchSaleAnnouncementUpdate.as_view(), name='sale_announcement_update'),
    path('announcement/<int:pk>/delete/', WatchSaleAnnouncementDelete.as_view(), name='sale_announcement_delete'),
    path('list/', SaleAnnouncementList.as_view(), name='sale_announcement_list'),
    path('list/search/', WatchSearchView.as_view(), name='sale_announcement_search_list'),
    path('mylist/', PersonalSaleAnnouncement.as_view(), name='my_sale_announcement_list'),
    path('<int:pk>/shop/', ProfileShopView.as_view(), name='sale_shop_list'),
    path('<int:pk>/confirmation/', ConfirmBuyView.as_view(), name='confirm_purchase'),
    path('<int:pk>/bought/', BoughtView.as_view(), name='watch_bought'),
]

wishlist/urls.py
from django.urls import path

from wishlist.views import WishListView, add_to_wishlist, remove_from_wishlist

app_name = 'wishlist'


urlpatterns = [
    path('list/', WishListView.as_view(), name='wishlist-all'),
    path('<int:pk>/add/', add_to_wishlist, name='wishlist-add'),
    path('<int:pk>/remove/', remove_from_wishlist, name='wishlist-remove')
]

templates/base.html
<!doctype html>
<html lang="it">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
          crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"
          crossorigin="anonymous">
    {% block style %}

    {% endblock %}

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% for message in messages %}
    <div class="alert
    {% if message.level == messages.SUCCESS %}
    alert-success
    {% elif message.level == messages.WARNING %}
    alert-warning
    {% elif message.level == messages.DANGER %}
    alert-danger
    {% else %}
    alert-info
    {% endif %}
    fade show alert-dismissible" role="alert">
        {{ message | safe }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endfor %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home' %}">Watch Market</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
                <div class="dropdown">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }}</button>

                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'profiles:user-detail' user.pk %}">My profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'wishlist:wishlist-all' %}">My Wishlist</a></li>
                        <li><a class="dropdown-item" href="{% url 'profiles:user-logout' %}">Logout</a></li>
                    </ul>
                </div>
            {% else %}
                <div class="dropdown">
                    <button class="btn bi bi-person dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'profiles:user-registration' %}">Register</a></li>
                        <li><a class="dropdown-item" href="{% url 'profiles:user-login' %}">Login</a></li>
                    </ul>
                </div>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'watches:sale_announcement_list' %}">All watches</a>
            </li>

            {% if user.is_authenticated and user.is_seller %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'watches:insert_sale_announcement' %}">Sell</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'watches:my_sale_announcement_list' %}">My announcement</a>
                </li>
            {% endif %}
            {% block nav-auth %}

            {% endblock %}
        </ul>
    </div>
</nav>

<main class="container">
    {% block content %}

    {% endblock %}
</main>

<!-- Footer -->
<footer class="page-footer font-small blue">
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">
        <a href="{% url 'home' %}"> WatchMarket.it </a>
        Created by: Federico Gibertoni
    </div>
    <!-- Copyright -->
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>
<script>
    $("#avanzate").hide();
    $("#drop-avanzate").click(function(){
        $("#avanzate").slideToggle();
    });

</script>
{% block script %}

{% endblock %}

</body>
</html>

templates/base_list.html
{% extends 'base.html' %}

{% block title %} List
    {% block list_title %}
    {% endblock %}
{% endblock %}

{% block content %}
    {% block pre_content %}

    {% endblock %}
    <h1>{% block content_title %}{% endblock %}</h1>
    <table class="table">
        <thead>
        <tr>
            {% block thead %}

            {% endblock %}
        </tr>
        </thead>
        <tbody>
        {% block tbody %}
        {% endblock %}
        </tbody>
    </table>
    {% block table_after %}
    {% endblock %}
    {#    <div class="pagination">#}
    {#        <span class="step-links">#}
    {#            {% if page_obj.has_previous %}#}
    {#                <a href="?page=1">&laquo; first</a>#}
    {#                <a href="?page={{ page_obj.previous_page_number }}">previous</a>#}
    {#            {% endif %}#}
    {##}
    {#            <span class="current">#}
    {#                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.#}
    {#            </span>#}
    {##}
    {#            {% if page_obj.has_next %}#}
    {#                <a href="?page={{ page_obj.next_page_number }}">next</a>#}
    {#                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>#}
    {#            {% endif %}#}
    {#        </span>#}
    {#    </div>#}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
            {% endif %}

            <li class="page-item active"><a class="page-link" id="actual-page-link" href="#">{{ page_obj.number }}</a></li>

            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

templates/homepage.html
{% extends 'base.html' %}
{% block title %}
    Watch Market
{% endblock %}

{% block content %}
    Welcome to this little watch market.
    <hr>
    <form method="get" action="{% url 'watches:sale_announcement_search_list' %}">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-10 mb-3">
                <div class="input-group" >
                    <input type="text" class="form-control" aria-label="Text input with dropdown button" id="query" placeholder="Watch brand" name="query-brand">
                    <input type="text" class="form-control" aria-label="Text input with dropdown button" id="query" placeholder="Watch model" name="query-model">
                    <button type="button" class="btn btn-outline-secondary" aria-label="Left Align" id="drop-avanzate">
                        <i class="fa fa-cog"></i>
                    </button>
                    <div class="input-group-append">
                        <button class="btn btn-primary"  type="submit" value="Submit" >Cerca</button>
                    </div>
                </div>
            </div>
            <div class="col-md-2 mb-3">
                <div class="input-group">
                    <label>Order by:</label>
                    <select name="order-by" class="custom-select">
                        <option value="p-asc">Price asc</option>
                        <option value="p-desc">Price desc</option>
                        <option value="date-asc">Date asc</option>
                        <option value="date-desc">Date desc</option>
                        <option value="year-asc">Year asc</option>
                        <option value="year-desc">Year desc</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row" id="avanzate">
            <div class="col-md-12">
                <div class="input-group mb-5" >
                    <input class="form-control" placeholder="Min price" type="number" name="start-price" min="0">
                    <input class="form-control" placeholder="Max price" type="number" name="end-price" min="0">
                    <input class="form-control" placeholder="Min year of production" type="number" name="start-year" min="0">
                    <input class="form-control" placeholder="Max year of production" type="number" name="end-year" min="0">
                    <input class="form-control" placeholder="Min case size" type="number" name="start-case-size" min="0">
                    <input class="form-control" placeholder="Max case size" type="number" name="end-case-size" min="0">
                    <input class="form-control" placeholder="Ref number" type="text" name="ref-number">
                    <select name="case-material" class="custom-select">
                        <option value="">Select case material</option>
                        <option value="STAINLESS_STEEL">Stainless Steel</option>
                        <option value="WHITE_GOLD">White Gold</option>
                        <option value="YELLOW_GOLD">Yellow Gold</option>
                        <option value="ROSE_GOLD">Rose Gold</option>
                        <option value="PLATINUM">Platinum</option>
                        <option value="TITANIUM">Titanium</option>
                        <option value="ALTRO">Altro</option>
                    </select>
                    <select name="bracelet-material" class="custom-select">
                        <option value="">Select bracelet material</option>
                        <option value="STAINLESS_STEEL">Stainless Steel</option>
                        <option value="WHITE_GOLD">White Gold</option>
                        <option value="YELLOW_GOLD">Yellow Gold</option>
                        <option value="ROSE_GOLD">Rose Gold</option>
                        <option value="PLATINUM">Platinum</option>
                        <option value="TITANIUM">Titanium</option>
                        <option value="LEATHER">Leather</option>
                        <option value="RUBBER">Rubber</option>
                        <option value="ALTRO">Altro</option>
                    </select>
                    <select name="conditions" class="custom-select">
                        <option value="">Select watch conditions</option>
                        <option value="NEW_NEVER_WORN">New/Never worn</option>
                        <option value="VERY_GOOD">Very Good</option>
                        <option value="GOOD">Good</option>
                        <option value="POOR">Poor</option>
                        <option value="NOT_WORKING">Not working</option>
                    </select>
                </div>
            </div>
        </div>

    </form>
{% endblock %}